import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { cn } from "@/lib/utils";
import AuthProvider from "@/providers/AuthProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn(inter.className, "antialiased")}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <main className="mx-auto p-4 sm:max-w-xl lg:max-w-3xl xl:max-w-7xl">
              <Toaster richColors position="top-center" />
              <Navbar />
              {children}
              <Footer />
            </main>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
