import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased")}>
        <ReactQueryProvider>
          <main className="mx-auto p-4 sm:max-w-xl lg:max-w-3xl xl:max-w-7xl">
            <Toaster richColors position="top-center" />
            <Navbar />
            {children}
            <Footer />
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
